# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SleepTracker' do

pod 'Google/Analytics', '~> 1.0.0'

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'

end

target 'SleepTrackerTests' do

end

